server:
  port: 8084

spring:
  application:
    name: dynamic-route-example

logging:
  level:
    root: INFO
    com.example: DEBUG
    com.strategy.starter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
